scrape_configs:
 - job_name: "prometheus"
  # Override the global default and scrape targets from this job every 5 seconds.
   scrape_interval: 1s
   static_configs:
      - targets: ["host.docker.internal:5149"]